---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)

data("ny_noaa")
```

```{r}
noaa_df = 
  ny_noaa%>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    prcp = as.numeric(prcp),
    prcp = prcp / 10,
    tmin = tmin / 10,
    tmax = tmax / 10,
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4
  ) %>% 
  select(id, year, month, day, prcp, snow, tmin, tmax)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A： Minium vs. Maximum tempreture at three selected station with snow and prcp

```{r}
noaa_df %>% 
  filter(year %in% 2001:2010, id %in% c("USW00094728", "USC00300331", "USC00300443"))%>% 
  mutate(
    text_label = str_c("Precipitation: ", prcp, "\nSnow: ", snow),
    name = recode(
      id,
      USW00094728 = "CentralPark",
      USC00300331 = "AURORA RESEARCH FARM",
      USC00300443 = "BATAVIA"
    )
  ) %>% 
  drop_na(tmin, tmax, snow) %>% 
  filter(snow != 0) %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~name, text = ~text_label, 
    alpha = .5, type = "scatter", mode = "markers", colors = "viridis")

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B： Precipitation: Rainy day at "USC00308~" NY station

```{r}
noaa_df %>% 
  mutate(id = fct_reorder(id, prcp)) %>% 
  filter(
    year %in% 2001:2010,
    prcp > 0,
    str_detect(id, "USC00308")
  ) %>% 
  plot_ly(y = ~prcp, color = ~id, type = "box", colors = "viridis")

```

### Chart C: Count of snowy day at "USC00308~" NY station

```{r}
noaa_df %>% 
  drop_na(snow) %>% 
  mutate(snow_day = if_else(snow > 0, "yes", "no")) %>% 
  filter(
    year %in% 2001:2010,
    snow_day == "yes",
    str_detect(id, "USC00308")
  ) %>%   
  count(id, snow_day) %>% 
  mutate(
    id = fct_reorder(id, n)
  ) %>% 
  plot_ly(x = ~id, y = ~n, color = ~id,
          type = "bar", colors = "viridis")

```

